spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tasklist?currentSchema=tasklist
    username: postgres
    password: 210791
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: YmxqYmlvSUJsYmxrYktCS05ramJuaU5vdW5rN3A4OWJrbmlhdWZpdWtzZG5mcA==
    access: 3600000
    refresh: 2592000000

server:
  port: 8097
